"""
src/training/run_logging.py

Shared TensorBoard + checkpoint infrastructure for every training/tuning/
evaluation run (closes the F1/F2 provenance findings from the 2026-08-19
metrics audit: the ensemble weight sweep had no artifact at all, and
LightGBM training had no manifest, no checksums, and no way to inspect
progress mid-run other than console logs).

Every script that trains, fine-tunes, or evaluates a model wraps its run in
a `RunLogger`:

    with RunLogger(run_type="xgboost", run_name="xgb_enhanced_features") as run_logger:
        trainer.train(X_train, y_train, X_val, y_val, run_logger=run_logger)

This creates two directories per run, both under project root and both
gitignored (see .gitignore — these are regenerated by every run, not
committed artifacts):

    runs/<run_type>/<run_name>_<UTC timestamp>/         TensorBoard event files
    checkpoints/<run_type>/<run_name>_<UTC timestamp>/  periodic model checkpoints

`tensorboard --logdir runs/` picks up every run across every model type at
once; each run's own subdirectory keeps its scalar curves from colliding
with another run's.

Checkpointing is deliberately NOT unified across XGBoost/LightGBM/TFT — each
library has its own native, non-pickle save format (Booster.save_model for
the two GBDTs, state_dict for TFT), and forcing one abstraction over three
different serialization formats would either lose the "no pickle" property
Phase D6 established or need a lossy common denominator. Instead this module
gives every trainer the same two primitives — `checkpoint_path()` for a
name, `prune_checkpoints()` for retention — and each trainer's own callback
decides what and how often to save.
"""

import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Union

from torch.utils.tensorboard import SummaryWriter

logger = logging.getLogger(__name__)


class RunLogger:
    """
    TensorBoard scalar logging + checkpoint directory management for one
    training/tuning/evaluation run.

    Not model-specific: XGBoost, LightGBM, and TFT trainers, plus the
    ensemble weight-sweep script, all use the same `log_scalar(s)` /
    `checkpoint_path()` / `prune_checkpoints()` calls — only the *content*
    they log differs.
    """

    def __init__(
        self,
        run_type: str,
        run_name: str,
        base_dir: Union[str, Path] = "runs",
        checkpoint_base_dir: Union[str, Path] = "checkpoints",
    ) -> None:
        """
        Args:
            run_type: top-level grouping, e.g. "xgboost", "lightgbm", "tft",
                "ensemble" — becomes a subdirectory under both `base_dir`
                and `checkpoint_base_dir`.
            run_name: human-readable name for this specific run, e.g.
                "xgb_enhanced_features" or an MLflow run ID prefix. Combined
                with a UTC timestamp to form a unique run directory so two
                runs with the same name never collide or silently overwrite
                each other's TensorBoard curves.
        """
        # Second-resolution timestamps alone collide when two RunLoggers are
        # constructed within the same wall-clock second (observed in tests
        # that create two back-to-back — a real risk if two training
        # scripts are ever launched together, not just a test artifact).
        # Microsecond resolution plus a short random suffix makes collision
        # practically impossible even across processes with skewed clocks.
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f")
        unique_suffix = uuid.uuid4().hex[:6]
        self.run_id = f"{run_name}_{timestamp}_{unique_suffix}"

        self.log_dir = Path(base_dir) / run_type / self.run_id
        self.checkpoint_dir = Path(checkpoint_base_dir) / run_type / self.run_id
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.checkpoint_dir.mkdir(parents=True, exist_ok=True)

        self._writer = SummaryWriter(log_dir=str(self.log_dir))
        logger.info(
            f"RunLogger started: TensorBoard logs -> {self.log_dir} "
            f"(tensorboard --logdir runs/), checkpoints -> {self.checkpoint_dir}"
        )

    def log_scalar(self, tag: str, value: float, step: int) -> None:
        """Write one scalar value at one step (e.g. a boosting round or epoch)."""
        self._writer.add_scalar(tag, value, step)

    def log_scalars(self, metrics: Dict[str, float], step: int) -> None:
        """Write several scalars that share the same step, e.g. every metric
        computed at the end of one epoch or boosting round."""
        for tag, value in metrics.items():
            if value is None:
                continue
            self._writer.add_scalar(tag, value, step)

    def checkpoint_path(self, step: int, suffix: str) -> Path:
        """
        Deterministic, sortable checkpoint filename for one step.

        Zero-padded to 6 digits so lexicographic sort (used by
        `prune_checkpoints`) matches numeric step order without parsing the
        filename back into an int.
        """
        return self.checkpoint_dir / f"checkpoint_step_{step:06d}.{suffix}"

    def prune_checkpoints(self, keep_last: int = 3) -> None:
        """
        Delete all but the `keep_last` most recent checkpoints in this run's
        checkpoint directory.

        Safe to call after every checkpoint write — a run directory is
        unique per `RunLogger` instance (timestamped), so this only ever
        prunes checkpoints from the *current* run, never a previous one.
        `keep_last <= 0` is treated as "keep everything" (no-op) rather than
        deleting all checkpoints, so a caller can't accidentally wipe a run
        by passing 0.
        """
        if keep_last <= 0:
            return
        files = sorted(self.checkpoint_dir.glob("checkpoint_step_*"))
        for stale in files[:-keep_last]:
            stale.unlink(missing_ok=True)

    def close(self) -> None:
        self._writer.flush()
        self._writer.close()

    def __enter__(self) -> "RunLogger":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.close()
